// Dados dos jogos.html
const listaJogos = [
  {
    id: 1,
    fase: "Final",
    time1: "Espanha",
    escudo1: "img/espanha.svg",
    time2: "Argentina",
    escudo2: "img/argentina.svg",
    placar: "1 a 0",
    local: "Estádio de Nova York · Domingo 19/07.",
  },
  {
    id: 2,
    fase: "Disputa pelo Terceiro Lugar",
    time1: "Inglaterra",
    escudo1: "img/inglaterra.svg",
    time2: "França",
    escudo2: "img/frança.svg",
    placar: "6 a 4",
    local: "Estádio de Miami · Sábado 18/07.",
  },
  {
    id: 3,
    fase: "SemiFinal",
    time1: "Argentina",
    escudo1: "img/argentina.svg",
    time2: "Inglaterra",
    escudo2: "img/inglaterra.svg",
    placar: "2 a 1",
    local: "Estádio de Atlanta · Quarta 15/07.",
  },
  {
    id: 4,
    fase: "SemiFinal",
    time1: "Espanha",
    escudo1: "img/espanha.svg",
    time2: "França",
    escudo2: "img/frança.svg",
    placar: "2 a 0",
    local: "Estádio de Dallas · Terça 14/07.",
  },
  {
    id: 5,
    fase: "Quartas de Final",
    time1: "Argentina",
    escudo1: "img/argentina.svg",
    time2: "Suíça",
    escudo2: "img/suiça.svg",
    placar: "3 a 1",
    local: "Estádio de Kansas City · Sábado 11/07.",
  },
  {
    id: 6,
    fase: "Quartas de Final",
    time1: "Inglaterra",
    escudo1: "img/inglaterra.svg",
    time2: "Noruega",
    escudo2: "img/noruega.svg",
    placar: "2 a 1",
    local: "Estádio de Miami · Sábado 11/07.",
  },
  {
    id: 7,
    fase: "Oitavas de final",
    time1: "Suíça",
    escudo1: "img/suiça.svg",
    time2: "Colômbia",
    escudo2: "img/colombia.svg",
    placar: "0 (4) a 0 (3)",
    local: "Data: 07/07",
  },
  {
    id: 8,
    fase: "Oitavas de final",
    time1: "Argentina",
    escudo1: "img/argentina.svg",
    time2: "Egito",
    escudo2: "img/egito.svg",
    placar: "3 a 2",
    local: "Data: 07/07",
  },
  {
    id: 9,
    fase: "Oitavas de final",
    time1: "Estados Unidos",
    escudo1: "img/estados-unidos.svg",
    time2: "Bélgica",
    escudo2: "img/belgica.svg",
    placar: "1 a 4",
    local: "Data: 06/07",
  },
  {
    id: 10,
    fase: "Oitavas de final",
    time1: "Portugal",
    escudo1: "img/portugal.svg",
    time2: "Espanha",
    escudo2: "img/espanha.svg",
    placar: "0 a 1",
    local: "Data: 06/07",
  },
  {
    id: 11,
    fase: "Oitavas de final",
    time1: "México",
    escudo1: "img/mexico.svg",
    time2: "Inglaterra",
    escudo2: "img/inglaterra.svg",
    placar: "2 a 3",
    local: "Data: 05/07",
  },
  {
    id: 12,
    fase: "Oitavas de final",
    time1: "Brasil",
    escudo1: "img/brasil.svg",
    time2: "Noruega",
    escudo2: "img/noruega.svg",
    placar: "1 a 2",
    local: "Data: 05/07",
  },
  {
    id: 13,
    fase: "Oitavas de final",
    time1: "Paraguai",
    escudo1: "img/paraguai.svg",
    time2: "França",
    escudo2: "img/frança.svg",
    placar: "0 a 1",
    local: "Data: 04/07",
  },
  {
    id: 14,
    fase: "Oitavas de final",
    time1: "Canadá",
    escudo1: "img/canada.svg",
    time2: "Marrocos",
    escudo2: "img/marrocos.svg",
    placar: "0 a 3",
    local: "Data: 04/07",
  },

  {
    id: 15,
    fase: "Segunda rodada",
    time1: "Colômbia",
    escudo1: "img/colombia.svg",
    time2: "Gana",
    escudo2: "img/gana.svg",
    placar: "1 a 0",
    local: "Data: 03/07",
  },
  {
    id: 16,
    fase: "Segunda rodada",
    time1: "Argentina",
    escudo1: "img/argentina.svg",
    time2: "Cabo Verde",
    escudo2: "img/cabo-verde.svg",
    placar: "3 a 2",
    local: "Data: 03/07 · Após prorrogação",
  },
  {
    id: 17,
    fase: "Segunda rodada",
    time1: "Austrália",
    escudo1: "img/australia.svg",
    time2: "Egito",
    escudo2: "img/egito.svg",
    placar: "1 (2) a 1 (4)",
    local: "Data: 03/07",
  },
  {
    id: 18,
    fase: "Segunda rodada",
    time1: "Suíça",
    escudo1: "img/suiça.svg",
    time2: "Argélia",
    escudo2: "img/argelia.svg",
    placar: "2 a 0",
    local: "Data: 03/07",
  },
  {
    id: 19,
    fase: "Segunda rodada",
    time1: "Portugal",
    escudo1: "img/portugal.svg",
    time2: "Croácia",
    escudo2: "img/croacia.svg",
    placar: "2 a 1",
    local: "Data: 02/07",
  },
  {
    id: 20,
    fase: "Segunda rodada",
    time1: "Espanha",
    escudo1: "img/espanha.svg",
    time2: "Áustria",
    escudo2: "img/austria.svg",
    placar: "3 a 0",
    local: "Data: 02/07",
  },
  {
    id: 21,
    fase: "Segunda rodada",
    time1: "Estados Unidos",
    escudo1: "img/estados-unidos.svg",
    time2: "Bósnia e Herzegovina",
    escudo2: "img/bosnia-e-herzegovina.svg",
    placar: "2 a 0",
    local: "Data: 01/07",
  },
  {
    id: 22,
    fase: "Segunda rodada",
    time1: "Bélgica",
    escudo1: "img/belgica.svg",
    time2: "Senegal",
    escudo2: "img/senegal.svg",
    placar: "3 a 2",
    local: "Data: 01/07 · Após prorrogação",
  },
  {
    id: 23,
    fase: "Segunda rodada",
    time1: "Inglaterra",
    escudo1: "img/inglaterra.svg",
    time2: "RD Congo",
    escudo2: "img/rd-congo.svg",
    placar: "2 a 1",
    local: "Data: 01/07",
  },
  {
    id: 24,
    fase: "Segunda rodada",
    time1: "México",
    escudo1: "img/mexico.svg",
    time2: "Equador",
    escudo2: "img/equador.svg",
    placar: "2 a 0",
    local: "Data: 30/06",
  },
  {
    id: 25,
    fase: "Segunda rodada",
    time1: "França",
    escudo1: "img/frança.svg",
    time2: "Suécia",
    escudo2: "img/suecia.svg",
    placar: "3 a 0",
    local: "Data: 30/06",
  },
  {
    id: 26,
    fase: "Segunda rodada",
    time1: "Costa do Marfim",
    escudo1: "img/costa-do-marfim.svg",
    time2: "Noruega",
    escudo2: "img/noruega.svg",
    placar: "1 a 2",
    local: "Data: 30/06",
  },
  {
    id: 27,
    fase: "Segunda rodada",
    time1: "Países Baixos",
    escudo1: "img/paises-baixos.svg",
    time2: "Marrocos",
    escudo2: "img/marrocos.svg",
    placar: "1 (2) a 1 (3)",
    local: "Data: 29/06",
  },
  {
    id: 28,
    fase: "Segunda rodada",
    time1: "Alemanha",
    escudo1: "img/alemanha.svg",
    time2: "Paraguai",
    escudo2: "img/paraguai.svg",
    placar: "1 (3) a 1 (4)",
    local: "Data: 29/06",
  },
  {
    id: 29,
    fase: "Segunda rodada",
    time1: "Brasil",
    escudo1: "img/brasil.svg",
    time2: "Japão",
    escudo2: "img/japao.svg",
    placar: "2 a 1",
    local: "Data: 29/06",
  },
  {
    id: 30,
    fase: "Segunda rodada",
    time1: "África do Sul",
    escudo1: "img/africa-do-sul.svg",
    time2: "Canadá",
    escudo2: "img/canada.svg",
    placar: "0 a 1",
    local: "Data: 28/06",
  },

  {
    id: 31,
    fase: "Grupo J",
    time1: "Jordânia",
    escudo1: "img/jordania.svg",
    time2: "Argentina",
    escudo2: "img/argentina.svg",
    placar: "1 a 3",
    local: "Data: 27/06",
  },
  {
    id: 32,
    fase: "Grupo J",
    time1: "Argélia",
    escudo1: "img/argelia.svg",
    time2: "Áustria",
    escudo2: "img/austria.svg",
    placar: "3 a 3",
    local: "Data: 27/06",
  },
  {
    id: 33,
    fase: "Grupo K",
    time1: "RD Congo",
    escudo1: "img/rd-congo.svg",
    time2: "Uzbequistão",
    escudo2: "img/uzbequistao.svg",
    placar: "3 a 1",
    local: "Data: 27/06",
  },
  {
    id: 34,
    fase: "Grupo K",
    time1: "Colômbia",
    escudo1: "img/colombia.svg",
    time2: "Portugal",
    escudo2: "img/portugal.svg",
    placar: "0 a 0",
    local: "Data: 27/06",
  },
  {
    id: 35,
    fase: "Grupo L",
    time1: "Croácia",
    escudo1: "img/croacia.svg",
    time2: "Gana",
    escudo2: "img/gana.svg",
    placar: "2 a 1",
    local: "Data: 27/06",
  },
  {
    id: 36,
    fase: "Grupo L",
    time1: "Panamá",
    escudo1: "img/panama.svg",
    time2: "Inglaterra",
    escudo2: "img/inglaterra.svg",
    placar: "0 a 2",
    local: "Data: 27/06",
  },
  {
    id: 37,
    fase: "Grupo G",
    time1: "Egito",
    escudo1: "img/egito.svg",
    time2: "Irã",
    escudo2: "img/ira.svg",
    placar: "1 a 1",
    local: "Data: 27/06",
  },
  {
    id: 38,
    fase: "Grupo G",
    time1: "Nova Zelândia",
    escudo1: "img/nova-zelandia.svg",
    time2: "Bélgica",
    escudo2: "img/belgica.svg",
    placar: "1 a 5",
    local: "Data: 27/06",
  },

  {
    id: 39,
    fase: "Grupo H",
    time1: "Uruguai",
    escudo1: "img/uruguai.svg",
    time2: "Espanha",
    escudo2: "img/espanha.svg",
    placar: "0 a 1",
    local: "Data: 26/06",
  },
  {
    id: 40,
    fase: "Grupo H",
    time1: "Cabo Verde",
    escudo1: "img/cabo-verde.svg",
    time2: "Arábia Saudita",
    escudo2: "img/arabia-saudita.svg",
    placar: "0 a 0",
    local: "Data: 26/06",
  },
  {
    id: 41,
    fase: "Grupo I",
    time1: "Senegal",
    escudo1: "img/senegal.svg",
    time2: "Iraque",
    escudo2: "img/iraque.svg",
    placar: "5 a 0",
    local: "Data: 26/06",
  },
  {
    id: 42,
    fase: "Grupo I",
    time1: "Noruega",
    escudo1: "img/noruega.svg",
    time2: "França",
    escudo2: "img/frança.svg",
    placar: "1 a 4",
    local: "Data: 26/06",
  },

  {
    id: 43,
    fase: "Grupo D",
    time1: "Paraguai",
    escudo1: "img/paraguai.svg",
    time2: "Austrália",
    escudo2: "img/australia.svg",
    placar: "0 a 0",
    local: "Data: 25/06",
  },
  {
    id: 44,
    fase: "Grupo D",
    time1: "Turquia",
    escudo1: "img/turquia.svg",
    time2: "Estados Unidos",
    escudo2: "img/estados-unidos.svg",
    placar: "3 a 2",
    local: "Data: 25/06",
  },
  {
    id: 45,
    fase: "Grupo F",
    time1: "Japão",
    escudo1: "img/japao.svg",
    time2: "Suécia",
    escudo2: "img/suecia.svg",
    placar: "1 a 1",
    local: "Data: 25/06",
  },
  {
    id: 46,
    fase: "Grupo F",
    time1: "Tunísia",
    escudo1: "img/tunisia.svg",
    time2: "Países Baixos",
    escudo2: "img/paises-baixos.svg",
    placar: "1 a 3",
    local: "Data: 25/06",
  },
  {
    id: 47,
    fase: "Grupo E",
    time1: "Equador",
    escudo1: "img/equador.svg",
    time2: "Alemanha",
    escudo2: "img/alemanha.svg",
    placar: "2 a 1",
    local: "Data: 25/06",
  },
  {
    id: 48,
    fase: "Grupo E",
    time1: "Curaçao",
    escudo1: "img/curacao.svg",
    time2: "Costa do Marfim",
    escudo2: "img/costa-do-marfim.svg",
    placar: "0 a 2",
    local: "Data: 25/06",
  },

  {
    id: 49,
    fase: "Grupo A",
    time1: "Tchéquia",
    escudo1: "img/tchequia.svg",
    time2: "México",
    escudo2: "img/mexico.svg",
    placar: "0 a 3",
    local: "Data: 24/06",
  },
  {
    id: 50,
    fase: "Grupo A",
    time1: "África do Sul",
    escudo1: "img/africa-do-sul.svg",
    time2: "Coreia do Sul",
    escudo2: "img/coreia-do-sul.svg",
    placar: "1 a 0",
    local: "Data: 24/06",
  },
  {
    id: 51,
    fase: "Grupo C",
    time1: "Escócia",
    escudo1: "img/escocia.svg",
    time2: "Brasil",
    escudo2: "img/brasil.svg",
    placar: "0 a 3",
    local: "Data: 24/06",
  },
  {
    id: 52,
    fase: "Grupo C",
    time1: "Marrocos",
    escudo1: "img/marrocos.svg",
    time2: "Haiti",
    escudo2: "img/haiti.svg",
    placar: "4 a 2",
    local: "Data: 24/06",
  },
  {
    id: 53,
    fase: "Grupo B",
    time1: "Bósnia e Herzegovina",
    escudo1: "img/bosnia-e-herzegovina.svg",
    time2: "Catar",
    escudo2: "img/catar.svg",
    placar: "3 a 1",
    local: "Data: 24/06",
  },
  {
    id: 54,
    fase: "Grupo B",
    time1: "Suíça",
    escudo1: "img/suiça.svg",
    time2: "Canadá",
    escudo2: "img/canada.svg",
    placar: "2 a 1",
    local: "Data: 24/06",
  },

  {
    id: 55,
    fase: "Grupo K",
    time1: "Colômbia",
    escudo1: "img/colombia.svg",
    time2: "RD Congo",
    escudo2: "img/rd-congo.svg",
    placar: "1 a 0",
    local: "Data: 23/06",
  },
  {
    id: 56,
    fase: "Grupo L",
    time1: "Panamá",
    escudo1: "img/panama.svg",
    time2: "Croácia",
    escudo2: "img/croacia.svg",
    placar: "0 a 1",
    local: "Data: 23/06",
  },
  {
    id: 57,
    fase: "Grupo L",
    time1: "Inglaterra",
    escudo1: "img/inglaterra.svg",
    time2: "Gana",
    escudo2: "img/gana.svg",
    placar: "0 a 0",
    local: "Data: 23/06",
  },
  {
    id: 58,
    fase: "Grupo K",
    time1: "Portugal",
    escudo1: "img/portugal.svg",
    time2: "Uzbequistão",
    escudo2: "img/uzbequistao.svg",
    placar: "5 a 0",
    local: "Data: 23/06",
  },
  {
    id: 59,
    fase: "Grupo J",
    time1: "Jordânia",
    escudo1: "img/jordania.svg",
    time2: "Argélia",
    escudo2: "img/argelia.svg",
    placar: "1 a 2",
    local: "Data: 23/06",
  },

  {
    id: 60,
    fase: "Grupo I",
    time1: "Noruega",
    escudo1: "img/noruega.svg",
    time2: "Senegal",
    escudo2: "img/senegal.svg",
    placar: "3 a 2",
    local: "Data: 22/06",
  },
  {
    id: 61,
    fase: "Grupo I",
    time1: "França",
    escudo1: "img/frança.svg",
    time2: "Iraque",
    escudo2: "img/iraque.svg",
    placar: "3 a 0",
    local: "Data: 22/06",
  },
  {
    id: 62,
    fase: "Grupo J",
    time1: "Argentina",
    escudo1: "img/argentina.svg",
    time2: "Áustria",
    escudo2: "img/austria.svg",
    placar: "2 a 0",
    local: "Data: 22/06",
  },

  {
    id: 63,
    fase: "Grupo G",
    time1: "Nova Zelândia",
    escudo1: "img/nova-zelandia.svg",
    time2: "Egito",
    escudo2: "img/egito.svg",
    placar: "1 a 3",
    local: "Data: 21/06",
  },
  {
    id: 64,
    fase: "Grupo H",
    time1: "Uruguai",
    escudo1: "img/uruguai.svg",
    time2: "Cabo Verde",
    escudo2: "img/cabo-verde.svg",
    placar: "2 a 2",
    local: "Data: 21/06",
  },
  {
    id: 65,
    fase: "Grupo G",
    time1: "Bélgica",
    escudo1: "img/belgica.svg",
    time2: "Irã",
    escudo2: "img/ira.svg",
    placar: "0 a 0",
    local: "Data: 21/06",
  },
  {
    id: 66,
    fase: "Grupo H",
    time1: "Espanha",
    escudo1: "img/espanha.svg",
    time2: "Arábia Saudita",
    escudo2: "img/arabia-saudita.svg",
    placar: "4 a 0",
    local: "Data: 21/06",
  },
  {
    id: 67,
    fase: "Grupo F",
    time1: "Tunísia",
    escudo1: "img/tunisia.svg",
    time2: "Japão",
    escudo2: "img/japao.svg",
    placar: "0 a 4",
    local: "Data: 21/06",
  },

  {
    id: 68,
    fase: "Grupo D",
    time1: "Turquia",
    escudo1: "img/turquia.svg",
    time2: "Paraguai",
    escudo2: "img/paraguai.svg",
    placar: "0 a 1",
    local: "Data: 20/06",
  },
  {
    id: 69,
    fase: "Grupo F",
    time1: "Países Baixos",
    escudo1: "img/paises-baixos.svg",
    time2: "Suécia",
    escudo2: "img/suecia.svg",
    placar: "5 a 1",
    local: "Data: 20/06",
  },
  {
    id: 70,
    fase: "Grupo E",
    time1: "Alemanha",
    escudo1: "img/alemanha.svg",
    time2: "Costa do Marfim",
    escudo2: "img/costa-do-marfim.svg",
    placar: "2 a 1",
    local: "Data: 20/06",
  },
  {
    id: 71,
    fase: "Grupo E",
    time1: "Equador",
    escudo1: "img/equador.svg",
    time2: "Curaçao",
    escudo2: "img/curacao.svg",
    placar: "0 a 0",
    local: "Data: 20/06",
  },

  {
    id: 72,
    fase: "Grupo D",
    time1: "Estados Unidos",
    escudo1: "img/estados-unidos.svg",
    time2: "Austrália",
    escudo2: "img/australia.svg",
    placar: "2 a 0",
    local: "Data: 19/06",
  },
  {
    id: 73,
    fase: "Grupo C",
    time1: "Escócia",
    escudo1: "img/escocia.svg",
    time2: "Marrocos",
    escudo2: "img/marrocos.svg",
    placar: "0 a 1",
    local: "Data: 19/06",
  },
  {
    id: 74,
    fase: "Grupo C",
    time1: "Brasil",
    escudo1: "img/brasil.svg",
    time2: "Haiti",
    escudo2: "img/haiti.svg",
    placar: "3 a 0",
    local: "Data: 19/06",
  },

  {
    id: 75,
    fase: "Grupo A",
    time1: "Tchéquia",
    escudo1: "img/tchequia.svg",
    time2: "África do Sul",
    escudo2: "img/africa-do-sul.svg",
    placar: "1 a 1",
    local: "Data: 18/06",
  },
  {
    id: 76,
    fase: "Grupo B",
    time1: "Suíça",
    escudo1: "img/suiça.svg",
    time2: "Bósnia e Herzegovina",
    escudo2: "img/bosnia-e-herzegovina.svg",
    placar: "4 a 1",
    local: "Data: 18/06",
  },
  {
    id: 77,
    fase: "Grupo B",
    time1: "Canadá",
    escudo1: "img/canada.svg",
    time2: "Catar",
    escudo2: "img/catar.svg",
    placar: "6 a 0",
    local: "Data: 18/06",
  },
  {
    id: 78,
    fase: "Grupo A",
    time1: "México",
    escudo1: "img/mexico.svg",
    time2: "Coreia do Sul",
    escudo2: "img/coreia-do-sul.svg",
    placar: "1 a 0",
    local: "Data: 18/06",
  },

  {
    id: 79,
    fase: "Grupo J",
    time1: "Áustria",
    escudo1: "img/austria.svg",
    time2: "Jordânia",
    escudo2: "img/jordania.svg",
    placar: "3 a 1",
    local: "Data: 17/06",
  },
  {
    id: 80,
    fase: "Grupo K",
    time1: "Portugal",
    escudo1: "img/portugal.svg",
    time2: "RD Congo",
    escudo2: "img/rd-congo.svg",
    placar: "1 a 1",
    local: "Data: 17/06",
  },
  {
    id: 81,
    fase: "Grupo L",
    time1: "Inglaterra",
    escudo1: "img/inglaterra.svg",
    time2: "Croácia",
    escudo2: "img/croacia.svg",
    placar: "4 a 2",
    local: "Data: 17/06",
  },
  {
    id: 82,
    fase: "Grupo L",
    time1: "Gana",
    escudo1: "img/gana.svg",
    time2: "Panamá",
    escudo2: "img/panama.svg",
    placar: "1 a 0",
    local: "Data: 17/06",
  },
  {
    id: 83,
    fase: "Grupo K",
    time1: "Uzbequistão",
    escudo1: "img/uzbequistao.svg",
    time2: "Colômbia",
    escudo2: "img/colombia.svg",
    placar: "1 a 3",
    local: "Data: 17/06",
  },

  {
    id: 84,
    fase: "Grupo I",
    time1: "França",
    escudo1: "img/franca.svg",
    time2: "Senegal",
    escudo2: "img/senegal.svg",
    placar: "3 a 1",
    local: "Data: 16/06",
  },
  {
    id: 85,
    fase: "Grupo I",
    time1: "Iraque",
    escudo1: "img/iraque.svg",
    time2: "Noruega",
    escudo2: "img/noruega.svg",
    placar: "1 a 4",
    local: "Data: 16/06",
  },
  {
    id: 86,
    fase: "Grupo J",
    time1: "Argentina",
    escudo1: "img/argentina.svg",
    time2: "Argélia",
    escudo2: "img/argelia.svg",
    placar: "3 a 0",
    local: "Data: 16/06",
  },
  {
    id: 87,
    fase: "Grupo H",
    time1: "Espanha",
    escudo1: "img/espanha.svg",
    time2: "Cabo Verde",
    escudo2: "img/cabo-verde.svg",
    placar: "0 a 0",
    local: "Data: 15/06",
  },
  {
    id: 88,
    fase: "Grupo G",
    time1: "Bélgica",
    escudo1: "img/belgica.svg",
    time2: "Egito",
    escudo2: "img/egito.svg",
    placar: "1 a 1",
    local: "Data: 15/06",
  },
  {
    id: 89,
    fase: "Grupo H",
    time1: "Arábia Saudita",
    escudo1: "img/arabia-saudita.svg",
    time2: "Uruguai",
    escudo2: "img/uruguai.svg",
    placar: "1 a 1",
    local: "Data: 15/06",
  },
  {
    id: 90,
    fase: "Grupo G",
    time1: "Irã",
    escudo1: "img/ira.svg",
    time2: "Nova Zelândia",
    escudo2: "img/nova-zelandia.svg",
    placar: "2 a 2",
    local: "Data: 15/06",
  },

  {
    id: 91,
    fase: "Grupo D",
    time1: "Austrália",
    escudo1: "img/australia.svg",
    time2: "Turquia",
    escudo2: "img/turquia.svg",
    placar: "2 a 0",
    local: "Data: 14/06",
  },
  {
    id: 92,
    fase: "Grupo E",
    time1: "Alemanha",
    escudo1: "img/alemanha.svg",
    time2: "Curaçao",
    escudo2: "img/curacao.svg",
    placar: "7 a 1",
    local: "Data: 14/06",
  },
  {
    id: 93,
    fase: "Grupo F",
    time1: "Países Baixos",
    escudo1: "img/paises-baixos.svg",
    time2: "Japão",
    escudo2: "img/japao.svg",
    placar: "2 a 2",
    local: "Data: 14/06",
  },
  {
    id: 94,
    fase: "Grupo E",
    time1: "Costa do Marfim",
    escudo1: "img/costa-do-marfim.svg",
    time2: "Equador",
    escudo2: "img/equador.svg",
    placar: "1 a 0",
    local: "Data: 14/06",
  },
  {
    id: 95,
    fase: "Grupo F",
    time1: "Suécia",
    escudo1: "img/suecia.svg",
    time2: "Tunísia",
    escudo2: "img/tunisia.svg",
    placar: "5 a 1",
    local: "Data: 14/06",
  },
  {
    id: 96,
    fase: "Grupo B",
    time1: "Canadá",
    escudo1: "img/canada.svg",
    time2: "Bósnia e Herzegovina",
    escudo2: "img/bosnia-e-herzegovina.svg",
    placar: "1 a 1",
    local: "Data: 12/06",
  },
  {
    id: 97,
    fase: "Grupo D",
    time1: "Estados Unidos",
    escudo1: "img/estados-unidos.svg",
    time2: "Paraguai",
    escudo2: "img/paraguai.svg",
    placar: "4 a 1",
    local: "Data: 12/06",
  },
  {
    id: 98,
    fase: "Grupo B",
    time1: "Catar",
    escudo1: "img/catar.svg",
    time2: "Suíça",
    escudo2: "img/suiça.svg",
    placar: "1 a 1",
    local: "Data: 13/06",
  },
  {
    id: 99,
    fase: "Grupo C",
    time1: "Brasil",
    escudo1: "img/brasil.svg",
    time2: "Marrocos",
    escudo2: "img/marrocos.svg",
    placar: "1 a 1",
    local: "Data: 13/06",
  },
  {
    id: 100,
    fase: "Grupo C",
    time1: "Haiti",
    escudo1: "img/haiti.svg",
    time2: "Escócia",
    escudo2: "img/escocia.svg",
    placar: "0 a 1",
    local: "Data: 13/06",
  },
  {
    id: 101,
    fase: "Grupo A",
    time1: "México",
    escudo1: "img/mexico.svg",
    time2: "África do Sul",
    escudo2: "img/africa-do-sul.svg",
    placar: "2 a 0",
    local: "Data: 11/06",
  },
  {
    id: 102,
    fase: "Grupo A",
    time1: "Coreia do Sul",
    escudo1: "img/coreia-do-sul.svg",
    time2: "Tchéquia",
    escudo2: "img/tchequia.svg",
    placar: "2 a 1",
    local: "Data: 11/06",
  },
];
